//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoLNamesBlackedOut.Strings.ja_JP {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoLNamesBlackedOut.Strings.ja_JP.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   WoLNamesBlackedOut について に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutMenuItem_Text {
            get {
                return ResourceManager.GetString("AboutMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright画像を追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add_Copyright_Content {
            get {
                return ResourceManager.GetString("Add_Copyright.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビットレート(Mbps) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BitrateSlideBar_Header {
            get {
                return ResourceManager.GetString("BitrateSlideBar.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    BlackedOutカラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlackedOutColorText_Text {
            get {
                return ResourceManager.GetString("BlackedOutColorText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///    BlackedOut 開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlackedOutStartButtonText_Text {
            get {
                return ResourceManager.GetString("BlackedOutStartButtonText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///    BlackedOutタイプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlackedOutTypeText_Text {
            get {
                return ResourceManager.GetString("BlackedOutTypeText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバッグログ出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DebugLogExport_Text {
            get {
                return ResourceManager.GetString("DebugLogExport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisableAudio_Content {
            get {
                return ResourceManager.GetString("DisableAudio.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェック時、出力動画から音声トラックを除外します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisableAudio_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("DisableAudio.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   経過: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ElapsedLabel_Text {
            get {
                return ResourceManager.GetString("ElapsedLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ElapsedUnit_Text {
            get {
                return ResourceManager.GetString("ElapsedUnit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(分): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string End_min_Header {
            get {
                return ResourceManager.GetString("End_min.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(秒): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string End_sec_Header {
            get {
                return ResourceManager.GetString("End_sec.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残り: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EtaLabel_Text {
            get {
                return ResourceManager.GetString("EtaLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EtaUnit_Text {
            get {
                return ResourceManager.GetString("EtaUnit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前で対象外を有効化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExcludeByNameEnabledCheckBox_Content {
            get {
                return ResourceManager.GetString("ExcludeByNameEnabledCheckBox.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///    固定マスクカラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FixedFrameColorText_Text {
            get {
                return ResourceManager.GetString("FixedFrameColorText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///    固定マスクタイプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FixedFrameTypeText_Text {
            get {
                return ResourceManager.GetString("FixedFrameTypeText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ForX(Twitter) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ForX_Content {
            get {
                return ResourceManager.GetString("ForX.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   幅1280px / 30FPS に制限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ForX_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("ForX.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPS: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FpsLabel_Text {
            get {
                return ResourceManager.GetString("FpsLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fps に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FpsUnit_Text {
            get {
                return ResourceManager.GetString("FpsUnit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TensorRTエンジンのビルドに成功しました！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InfoBar_Message {
            get {
                return ResourceManager.GetString("InfoBar.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語UI（再起動後） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageJP_Text {
            get {
                return ResourceManager.GetString("LanguageJP.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライセンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LicenseButton_Text {
            get {
                return ResourceManager.GetString("LicenseButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoreAppBarButton_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("MoreAppBarButton.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画レンダリング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MovieRenderingSectionTitle_Text {
            get {
                return ResourceManager.GetString("MovieRenderingSectionTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象外名設定... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenExcludeByNameSettingsButton_Content {
            get {
                return ResourceManager.GetString("OpenExcludeByNameSettingsButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileText_Text {
            get {
                return ResourceManager.GetString("OpenFileText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   段階的パフォーマンスモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptimizationModeComboBox_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("OptimizationModeComboBox.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビュー開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreviewButtonText_Text {
            get {
                return ResourceManager.GetString("PreviewButtonText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビュー画像上で:
        /// 左クリック : 固定マスクを設定
        /// 右クリック : 固定マスクをすべて解除
        /// CTRL + 左ドラッグ : Copyright画像を移動
        /// CTRL + マウスホイール : Copyright画像を拡大縮小 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreviewHelpText_Text {
            get {
                return ResourceManager.GetString("PreviewHelpText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreviewSectionTitle_Text {
            get {
                return ResourceManager.GetString("PreviewSectionTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   進行状況 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressSectionTitle_Text {
            get {
                return ResourceManager.GetString("ProgressSectionTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///    BlackedOut開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Runtime_BlackedOutStart {
            get {
                return ResourceManager.GetString("Runtime.BlackedOutStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///    BlackedOut停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Runtime_BlackedOutStop {
            get {
                return ResourceManager.GetString("Runtime.BlackedOutStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビュー開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Runtime_PreviewStart {
            get {
                return ResourceManager.GetString("Runtime.PreviewStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビュー停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Runtime_PreviewStop {
            get {
                return ResourceManager.GetString("Runtime.PreviewStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveImageButton_Label {
            get {
                return ResourceManager.GetString("SaveImageButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビュー画像を保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveImageButton_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("SaveImageButton.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright画像を選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectCopyrightImageButton_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("SelectCopyrightImageButton.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル選択 / ドラッグ＆ドロップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectFileSectionTitle_Text {
            get {
                return ResourceManager.GetString("SelectFileSectionTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingSectionTitle_Text {
            get {
                return ResourceManager.GetString("SettingSectionTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///    終了位置に設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetToEndText_Text {
            get {
                return ResourceManager.GetString("SetToEndText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///    開始位置に設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetToStartText_Text {
            get {
                return ResourceManager.GetString("SetToStartText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始(分): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Start_min_Header {
            get {
                return ResourceManager.GetString("Start_min.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始(秒): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Start_sec_Header {
            get {
                return ResourceManager.GetString("Start_sec.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StopText_Text {
            get {
                return ResourceManager.GetString("StopText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーマ切替 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToggleThemeButton_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("ToggleThemeButton.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YOLO しきい値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YoloThresholdSlider_Header {
            get {
                return ResourceManager.GetString("YoloThresholdSlider.Header", resourceCulture);
            }
        }
    }
}
