<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <RootNamespace>WoLNamesBlackedOut</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <Nullable>enable</Nullable>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSdkBootstrapInitialize>false</WindowsAppSdkBootstrapInitialize>
    <WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize>
    <WindowsAppSdkUndockedRegFreeWinRTInitialize>false</WindowsAppSdkUndockedRegFreeWinRTInitialize>
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="ffmpeg-master-latest-win64-gpl-shared\**" />
    <Compile Remove="opencv-cuda\**" />
    <Compile Remove="tensorrt_dll\**" />
    <Content Remove="ffmpeg-master-latest-win64-gpl-shared\**" />
    <Content Remove="opencv-cuda\**" />
    <Content Remove="tensorrt_dll\**" />
    <EmbeddedResource Remove="ffmpeg-master-latest-win64-gpl-shared\**" />
    <EmbeddedResource Remove="opencv-cuda\**" />
    <EmbeddedResource Remove="tensorrt_dll\**" />
    <None Remove="ffmpeg-master-latest-win64-gpl-shared\**" />
    <None Remove="opencv-cuda\**" />
    <None Remove="tensorrt_dll\**" />
    <Page Remove="ffmpeg-master-latest-win64-gpl-shared\**" />
    <Page Remove="opencv-cuda\**" />
    <Page Remove="tensorrt_dll\**" />
    <PRIResource Remove="ffmpeg-master-latest-win64-gpl-shared\**" />
    <PRIResource Remove="opencv-cuda\**" />
    <PRIResource Remove="tensorrt_dll\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="avcodec-62.dll" />
    <None Remove="avdevice-62.dll" />
    <None Remove="avfilter-11.dll" />
    <None Remove="avformat-62.dll" />
    <None Remove="avutil-60.dll" />
    <None Remove="best_slim_fp16.onnx" />
    <None Remove="codexffmpeg-8.1.2.zip" />
    <None Remove="cublas64_12.dll" />
    <None Remove="cublasLt64_12.dll" />
    <None Remove="cudnn_cnn64_9.dll" />
    <None Remove="cufft64_11.dll" />
    <None Remove="cufftw64_11.dll" />
    <None Remove="deepfillv2_mod_simp_fp16.onnx" />
    <None Remove="ffmpeg.exe" />
    <None Remove="ffmpeg_source.zip" />
    <None Remove="ffplay.exe" />
    <None Remove="ffprobe.exe" />
    <None Remove="libbz2-1.dll" />
    <None Remove="libgcc_s_seh-1.dll" />
    <None Remove="libiconv-2.dll" />
    <None Remove="liblzma-5.dll" />
    <None Remove="libstdc++-6.dll" />
    <None Remove="libvpl-2.dll" />
    <None Remove="libwinpthread-1.dll" />
    <None Remove="libzimg-2.dll" />
    <None Remove="my_yolov8m_s.onnx" />
    <None Remove="my_yolov8m_s.onnx_" />
    <None Remove="my_yolov8m_s_32.onnx" />
    <None Remove="my_yolov8m_s_dy.onnx" />
    <None Remove="my_yolov8m_s_dy.onnx_" />
    <None Remove="nppc64_12.dll" />
    <None Remove="nppial64_12.dll" />
    <None Remove="nppicc64_12.dll" />
    <None Remove="nppidei64_12.dll" />
    <None Remove="nppif64_12.dll" />
    <None Remove="nppig64_12.dll" />
    <None Remove="nppim64_12.dll" />
    <None Remove="nppist64_12.dll" />
    <None Remove="nppisu64_12.dll" />
    <None Remove="nppitc64_12.dll" />
    <None Remove="npps64_12.dll" />
    <None Remove="nvblas64_12.dll" />
    <None Remove="nvinfer_10.dll" />
    <None Remove="nvinfer_builder_resource_10.dll" />
    <None Remove="nvonnxparser_10.dll" />
    <None Remove="opencv_world4100.dll" />
    <None Remove="opencv_world4130.dll" />
    <None Remove="opencv_world4130.dll_bk" />
    <None Remove="ppocrv5_en_dict.txt" />
    <None Remove="swresample-6.dll" />
    <None Remove="swscale-9.dll" />
    <None Remove="tensorrt_onnxparser_rtx_1_2.dll" />
    <None Remove="tensorrt_onnxparser_rtx_1_3.dll" />
    <None Remove="tensorrt_rtx_1_2.dll" />
    <None Remove="tensorrt_rtx_1_3.dll" />
    <None Remove="WoLNamesBlackedOut_DLL.dll" />
    <None Remove="zlib1.dll" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="avcodec-62.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="avfilter-11.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="avformat-62.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="avutil-60.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ffmpeg.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ffmpeg_source.zip">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ffprobe.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="libwinpthread-1.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="my_yolov8m_s.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="c_ppocr-v5-rec_sim.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ppocrv5_en_dict.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="swresample-6.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="swscale-9.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="WoLNamesBlackedOut.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="WoLNamesBlackedOut_DLL.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\WoLNamesBlackedOut_DLL\WoLNamesBlackedOut_DLL.vcxproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <OutputItemType>Content</OutputItemType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Targets>Build</Targets>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="$(NuGetPackageRoot)microsoft.windowsappsdk.foundation\*\include\WindowsAppRuntimeAutoInitializer.cs" />
    <Compile Remove="$(NuGetPackageRoot)microsoft.windowsappsdk.foundation\*\include\MddBootstrapAutoInitializer.cs" />
    <Compile Remove="$(NuGetPackageRoot)microsoft.windowsappsdk.foundation\*\include\DeploymentManagerAutoInitializer.cs" />
    <Compile Remove="$(NuGetPackageRoot)microsoft.windowsappsdk.foundation\*\include\UndockedRegFreeWinRT-AutoInitializer.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="C_SQUARE_ENIX.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PRIResource Update="Strings\ja-JP\Resources.resw">
      <Generator></Generator>
    </PRIResource>
  </ItemGroup>

  <PropertyGroup Label="Globals">
    <WebView2EnableCsWinRTProjection>False</WebView2EnableCsWinRTProjection>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PublishProfile)'=='win-x64' or '$(PublishProfile)'=='win-x64.pubxml'">
    <PublishProfile>$(MSBuildProjectDirectory)\Properties\PublishProfiles\win-x64.pubxml</PublishProfile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Properties\PublishProfiles\win-x64.pubxml" />
  </ItemGroup>

  <ItemGroup>
    <None Update="DirectML.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Microsoft.Windows.AI.MachineLearning.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="onnxruntime.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

    <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">False</PublishReadyToRun>
    <PublishTrimmed>false</PublishTrimmed>
    <AssemblyName>WoLNamesBlackedOut</AssemblyName>
    <ApplicationIcon>WoLNamesBlackedOut.ico</ApplicationIcon>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  <Target Name="PostPublish" AfterTargets="Publish">
    <Exec Command="xcopy &quot;$(ProjectDir)..\..\WoLNamesBlackedOut_DLL\x64\$(Configuration)\WoLNamesBlackedOut_DLL.dll&quot; &quot;$(PublishDir)&quot; /y /d&#xD;&#xA;xcopy &quot;$(ProjectDir)..\..\packages\Microsoft.ML.OnnxRuntime.DirectML.1.24.3\runtimes\win-x64\native\onnxruntime.dll&quot; &quot;$(PublishDir)&quot; /y /d&#xD;&#xA;xcopy &quot;$(ProjectDir)..\..\packages\Microsoft.ML.OnnxRuntime.DirectML.1.24.3\runtimes\win-x64\native\onnxruntime_providers_shared.dll&quot; &quot;$(PublishDir)&quot; /y /d" />
  </Target>
</Project>